USE [master]
GO

/****** Object:  Database [psscV101]    Script Date: 1/6/2023 6:54:25 PM ******/
CREATE DATABASE [psscV101]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'psscV101', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\psscV101.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'psscV101_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\psscV101_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [psscV101].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [psscV101] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [psscV101] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [psscV101] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [psscV101] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [psscV101] SET ARITHABORT OFF 
GO

ALTER DATABASE [psscV101] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [psscV101] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [psscV101] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [psscV101] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [psscV101] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [psscV101] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [psscV101] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [psscV101] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [psscV101] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [psscV101] SET  ENABLE_BROKER 
GO

ALTER DATABASE [psscV101] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [psscV101] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [psscV101] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [psscV101] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [psscV101] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [psscV101] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [psscV101] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [psscV101] SET RECOVERY FULL 
GO

ALTER DATABASE [psscV101] SET  MULTI_USER 
GO

ALTER DATABASE [psscV101] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [psscV101] SET DB_CHAINING OFF 
GO

ALTER DATABASE [psscV101] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [psscV101] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [psscV101] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [psscV101] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [psscV101] SET QUERY_STORE = OFF
GO

ALTER DATABASE [psscV101] SET  READ_WRITE 
GO

